### ISSUE TITLE
Python Sudoku Solver Program

### ISSUE THREAD

**Issue by Vivek-raj-gupta-2002** [StepJes/Python-Code#12]
This program will help to solve sudoku with back tracing algorithm!!
it will take input in the matrix form of n X n, and the gives the output in the same n X n matrix

**Comment by Shreya111111** [comment]
@Vivek-raj-gupta-2002 plz assign this program to me .

**Comment by Vivek-raj-gupta-2002** [comment]
@Shreya111111 I am not its maintainer !! please contact @StepJes

**Comment by Vivek-raj-gupta-2002** [comment]
heyy!! Please Assign this to me

**Comment by Vivek-raj-gupta-2002** [comment]
I am having the code already!! please @StepJes

**Comment by alirah75** [comment]
please assign this program to me .

**Comment by Shreya111111** [comment]
@StepJes added python suduko solver pull request #20

**Comment by Shreya111111** [comment]
@StepJes added python suduko solver code plz check it once
