### ISSUE TITLE
Python program to calculate Body mass index

### ISSUE THREAD

**Issue by zcsop1206** [StepJes/Python-Code#14]
Please assign this issue to me. Thank you.

**Comment by zcsop1206** [comment]
Thank you!

**Comment by JJsdxd** [comment]
Can I get this issue assigned to me too please ,thank you.

**Comment by Coder404x2** [comment]
hey ,
I'm Manasi Deshmukh
form mksss ccoew
computer engineering SY

i would like to work on this issue
can you assign me this issue?

**Comment by Viren0602** [comment]
Hello sir , can you assign this issue to me?

**Comment by Chirag-v09** [comment]
Hi, I have created a pull request for the issue that you mentioned.
Do let me know if you need any further changes.

Thanks

**Comment by zcsop1206** [comment]
![image](https://user-images.githubusercontent.com/115398989/198509751-8b073e34-ba1b-42f3-a9d1-96162c261f97.png)
The file attached by me is working as intended
so i will be closing this issue

**Comment by Chirag-v09** [comment]
That's great news!
Also, I have created a python version of the BMI calculator. It would be great if you check that pull request and accept it.

Thanks
